version: '3.5'
 traefik:
    container_name: traefik
    image: traefik:v2.4
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.yml:/etc/traefik/traefik.yml
    - ./conf:/conf
    network_mode: host
    logging:
      options:
        max-size: 50m
